"""
Internet lockdown for macOS via the built-in packet filter (pf).

Strategy
--------
We replace pf's *main* active ruleset with one that:
  * skips all loopback traffic (so localhost / the master keeps working),
  * allows DHCP and mDNS (so the LAN doesn't break),
  * allows traffic to/from each whitelisted master IP,
  * blocks all other outbound traffic.

On release we re-load /etc/pf.conf to restore whatever the user
originally had. This is more reliable than the anchor-based approach,
because anchors only filter when /etc/pf.conf references them — which
we can't guarantee without modifying a system file.

Privilege requirements
----------------------
Every pfctl invocation needs root. The supported deployments are:
  * Install the client as a LaunchDaemon (runs as root):
        packaging/io.classcontrol.client.plist
  * OR install the bundled sudoers drop-in (narrowly scoped to pfctl):
        packaging/classcontrol-sudoers

If neither is in place, ``enable_lockdown`` returns ``{"ok": False,
"reason": "…"}`` so the master can surface a clear error instead of
appearing to succeed silently.
"""

from __future__ import annotations

import os
import subprocess
import tempfile
from pathlib import Path

from client.macos._priv import run_privileged, run_privileged_batch


ACTIVE_RULES_PATH = Path("/etc/pf.anchors/classcontrol-active")


_RULES_TEMPLATE = """# Generated by ClassControl. Loaded as pf's main ruleset while
# internet lockdown is on. Re-loaded /etc/pf.conf on release.

set skip on lo0
pass in quick proto udp from any port 67:68 to any port 67:68 keep state
pass out quick proto udp from any port 67:68 to any port 67:68 keep state
pass quick proto udp from any to 224.0.0.0/4 keep state
pass quick proto udp from any to any port 5353 keep state

{master_rules}

block drop out quick proto { tcp udp icmp } from any to any
"""


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _format_master_rules(master_ips: list[str]) -> str:
    parts: list[str] = []
    for ip in master_ips:
        parts.append(f"pass quick from any to {ip} keep state")
        parts.append(f"pass quick from {ip} to any keep state")
    return "\n".join(parts)


# Note: rule install + pfctl invocation are now a single privileged batch
# (see enable_lockdown below). This function is kept only as a fallback
# for paths that can write directly.
def _write_active_rules_direct(rules: str) -> bool:
    try:
        ACTIVE_RULES_PATH.parent.mkdir(parents=True, exist_ok=True)
        ACTIVE_RULES_PATH.write_text(rules)
        return True
    except PermissionError:
        return False


# ---------------------------------------------------------------------------
# Public API — return structured results so the master can show errors
# ---------------------------------------------------------------------------


def enable_lockdown(master_ips: list[str]) -> dict:
    """Block all outbound traffic except to ``master_ips``.

    Returns ``{"ok": bool, "reason": str}``. Generates ONE password
    prompt total (or zero if running as root / with a sudoers entry).
    """
    ips = [ip.strip() for ip in (master_ips or []) if ip and ip.strip()]
    if not ips:
        return {"ok": False, "reason": "no master IPs supplied"}

    rules = _RULES_TEMPLATE.format(master_rules=_format_master_rules(ips))

    # Spill the desired rules to a temp file (no privileges needed) and
    # do all the privileged work in one batched call.
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".pf.classcontrol", delete=False,
    ) as fh:
        fh.write(rules)
        tmp_path = fh.name

    try:
        # `pfctl -e -f file` enables pf and loads the ruleset in one go.
        rc, out, err = run_privileged_batch([
            ["cp", tmp_path, str(ACTIVE_RULES_PATH)],
            ["pfctl", "-e", "-f", str(ACTIVE_RULES_PATH)],
        ])
        if rc != 0:
            return {"ok": False, "reason":
                    (err.strip() or out.strip() or
                     "pfctl failed — needs root, sudoers, or admin prompt approval")}
        return {"ok": True, "reason": ""}
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


def disable_lockdown() -> dict:
    """Restore the original /etc/pf.conf ruleset."""
    rc, out, err = run_privileged(["pfctl", "-f", "/etc/pf.conf"])
    if rc != 0:
        return {"ok": False, "reason":
                (err.strip() or out.strip() or "pfctl restore failed")}
    return {"ok": True, "reason": ""}


def is_active() -> bool:
    rc, out, _ = run_privileged(["pfctl", "-sr"])
    return rc == 0 and "ClassControl" in out
